export const ADD_FAVOURITE_REQUEST = 'ADD_FAVOURITE_REQUEST';
export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS';
export const ADD_FAVOURITE_FAIL = 'ADD_FAVOURITE_FAIL';

export const APPLY_SEARCH_REQUEST = 'APPLY_SEARCH_REQUEST';
export const APPLY_SEARCH_SUCCESS = 'APPLY_SEARCH_SUCCESS';
export const APPLY_SEARCH_FAIL = 'APPLY_SEARCH_FAIL';

export const APPLY_FILTERS_REQUEST = 'APPLY_FILTERS_REQUEST';
export const APPLY_FILTERS_SUCCESS = 'APPLY_FILTERS_SUCCESS';
export const APPLY_FILTERS_FAIL = 'APPLY_FILTERS_FAIL';
