export const ADD_FAVOURITE_SUCCESS = 'ADD_FAVOURITE_SUCCESS';
export const ADD_FAVOURITE_FAIL = 'ADD_FAVOURITE_FAIL';

export const APPLY_SEARCH_SUCCESS = 'APPLY_SEARCH_SUCCESS';
export const APPLY_SEARCH_FAIL = 'APPLY_SEARCH_FAIL';

export const APPLY_FILTERS_SUCCESS = 'APPLY_FILTERS_SUCCESS';
export const APPLY_FILTERS_FAIL = 'APPLY_FILTERS_FAIL';

export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";